### ISSUE TITLE
Not really an issue but a feature request

### ISSUE THREAD

**Issue by rEd2k** [Mika-/torrent-control#16] opened 2018-03-09 07:04 UTC
So far this works great for me, but I am hoping maybe a simple left-click to send / capture the torrent over to the manager would be possible instead of always having to right-click for a context menu to send the torrent over. Is this a possibility?

**Comment by Mika-** [comment] 2018-03-10 10:01
This is duplicate of #10 
It's starting to look like firefox won't be getting proper apis for this any time soon. So it's time to start building some kind of alternative solution.

**Closed by Mika-** 2018-03-10 10:01 UTC
