### ISSUE TITLE
v0.2.16 doesn't work

### ISSUE THREAD

**Issue by mhe84** [Mika-/torrent-control#87] opened 2020-03-23 13:34 UTC
Greetings,

Torrent Control no longer works after latest update. I managed to get it working by reinstalling the addon, but once Firefox is closed it stops working again.

- Clicking 'Torrent Control' button does nothing
- Trying to open magnet link opens page "Unable to connect - Firefox can’t establish a connection to the server at torrent-control.invalid."

I'm using the client option "qBittorrent (<=4.0.4)" if that matters.

Hope you can fix. Meanwhile is there anyway I can roll back to previous version?

**Comment by Mika-** [comment] 2020-03-23 14:38
Looks like there's regression with clients without extra options. This will be fixed in a a moment.

**Closed** 2020-03-23 14:41 UTC
Labels: bug
