### ISSUE TITLE
Some torrent links are triggering Firefox download dialog instead

### ISSUE THREAD

**Issue by spidey** [Mika-/torrent-control#109] opened 2021-02-05 20:25 UTC
I have Catch torrent URLs and Magnet Links associated with Torrent Control on Firefox settings. Normal torrent association doesn't show Torrent Control as an option, but the Catch torrent URLs feature is making sure that they are routed to Torrent Control anyway. But I've found a website whose torrent links doesn't trigger Torrent Control, triggering the normal Firefox download dialog instead.

The URL format is `https://<domain>/view/<numeric_id>/torrent`, a pretty standard REST API. Is the problem that the URL catcher expects actual files, so anything ending with `.torrent`? Also, Torrent Control doesn't show up as an option, as an application that could handle the file (which is indeed a `.torrent` file as recognized by Firefox). Can I force it to open torrents like that?

**Comment by spidey** [comment] 2021-02-07 22:07
I'm not sure if it's allowed to post links here, the one specifically is from a well known anime fansub website. If helpful I can definitely provide an example.

**Comment by Mika-** [comment] 2021-02-08 14:06
This is mostly duplicate of #37 and #74. I have been waiting Mozilla to implement content handlers ([bugzilla 1457500](https://bugzilla.mozilla.org/show_bug.cgi?id=1457500)), which would allow Torrent control to act as default application for torrent files. Unfortunately that functionality has been constantly postponed.

Current catching mechanism uses hard coded [regexp list](https://github.com/Mika-/torrent-control/blob/master/src/util.js#L184-L198), which has worked fine for most of the users. My next development focus is most likely to make it user editable.

**Closed** 2021-04-01 06:38 UTC
Labels: enhancement
